language: python
cache: pip

python:
  - "3.6"
  - "3.4"
  - "3.5"

env:
  - TEST_TYPE="test"

matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="compliance"

install:
  - pip install .[dev]

script:
  - if [ "$TEST_TYPE" == "compliance" ] ; then pre-commit run --all-files
  - if [ "$TEST_TYPE" == "test" ] ; then cd tests; py.test --no-plot-compare

stages:
  - compliance
  - test
