language: python
cache: pip
sudo: true

python:
    - "3.4"
    - "3.5"
    - "3.6"

# before_install:
#     - sudo apt-get update -qq
#     - sudo apt-get install -qq liblapack.so 

install:
    - pip install matplotlib tbmodels
    - pip install .

# run tests
script:
    - cd tests
    - py.test --no-plot-compare
